Fix installation conflict with polkit
Error: Transaction check error:
  file /usr/share/polkit-1/rules.d from install of systemd-233-1.fc27.x86_64 conflicts with file from package polkit-0.113-7.fc26.x86_64